In [2]:
import numpy as np

In [3]:
arr=np.arange(4,15)

In [4]:
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr[8]

12

In [6]:
arr[1:5]

array([5, 6, 7, 8])

In [7]:
arr[:7]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[5:]

array([ 9, 10, 11, 12, 13, 14])

In [9]:
arr[1:5] =100

In [10]:
arr

array([  4, 100, 100, 100, 100,   9,  10,  11,  12,  13,  14])

In [11]:
arr=np.arange(4,15)

In [12]:
slice_of_arr=arr[1:6]

In [13]:
slice_of_arr

array([5, 6, 7, 8, 9])

In [14]:
slice_of_arr[:]=99

In [15]:
arr

array([ 4, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14])

In [16]:
matrix=np.array(([5,10,15],[20,25,30],[35,40,45]))

matrix= np.array(([1,2,3],[4,5,6],[7,8,9]))

In [17]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
matrix = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [17]:
matrix[0]

array([ 5, 10, 15])

In [18]:
matrix[2][1]

40

In [19]:
matrix[2,1]

40

In [20]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr = np.arange(0,10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [35]:
arr[arr>4]

array([5, 6, 7, 8, 9])

In [36]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
arr[[0,0,0,0,1,1,1,1,1,1]]

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [39]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [40]:
np.max(arr)

9

In [43]:
arr.max()

9

In [44]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
matrix.max(axis=1)

array([15, 30, 45])

In [46]:
matrix.max(axis=0)

array([35, 40, 45])