In [1]:
import numpy as np

## NumPy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## NumPy Methods

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
matrix=np.array(my_matrix)

In [12]:
matrix*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [13]:
matrix+matrix

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [17]:
np.ones((2,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [19]:
np.linspace(0,20,11)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

In [21]:
np.eye(3)
# identiy matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [22]:
np.random.rand(2)*5

array([ 0.41496003,  0.26926177])

In [23]:
np.random.randint(1,100)

83

In [24]:
np.random.rand(3,5)

array([[ 0.01318275,  0.29425474,  0.76986179,  0.46087138,  0.35376351],
       [ 0.43387244,  0.00443569,  0.29942765,  0.60538173,  0.35528352],
       [ 0.7765734 ,  0.4123072 ,  0.99194677,  0.25342792,  0.87643603]])

In [28]:
np.random.randint(1,100,(10,10))

array([[46, 91,  6, 42, 25, 24, 80, 91, 82, 74],
       [63, 17, 20, 84, 74, 83, 62, 48, 97, 86],
       [23, 20,  9, 83, 39, 34, 22, 21, 59, 76],
       [50, 61,  1, 75, 26, 96, 23, 56, 30, 29],
       [32, 30, 84, 35, 42, 19, 14,  9, 55, 63],
       [94, 15, 79, 26, 15, 26, 26, 58, 60, 76],
       [73, 96, 21,  9, 86, 45,  6, 57, 71, 95],
       [44, 69, 44, 64, 94, 43, 70, 56, 97,  1],
       [28, 99, 61, 67, 67, 96, 91, 11, 38, 46],
       [18, 99, 93, 65, 54, 96, 38, 53, 53, 22]])

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
np.random.randn(100)*.1+1.6

array([ 1.53568376,  1.62256071,  1.52728565,  1.68548893,  1.61482758,
        1.53362929,  1.59542076,  1.68441411,  1.75606928,  1.64508117,
        1.82366506,  1.54462221,  1.67185631,  1.61102921,  1.55832616,
        1.52673935,  1.61891699,  1.59908156,  1.46007936,  1.56905325,
        1.54490735,  1.76391839,  1.58387881,  1.72349778,  1.723878  ,
        1.47235787,  1.6315132 ,  1.58812732,  1.63495163,  1.57853839,
        1.76353992,  1.64096561,  1.54161728,  1.38875878,  1.61492943,
        1.52127185,  1.45742712,  1.76749823,  1.45508659,  1.64149054,
        1.51450468,  1.59340886,  1.80164274,  1.64193509,  1.68718138,
        1.58929887,  1.5856423 ,  1.65000307,  1.36908678,  1.5811472 ,
        1.56998915,  1.47840851,  1.48802149,  1.56412525,  1.5860461 ,
        1.64518943,  1.62462808,  1.59905815,  1.57856835,  1.54848236,
        1.57978943,  1.70179054,  1.79946432,  1.66678349,  1.61483548,
        1.51241373,  1.64202513,  1.51185106,  1.69186832,  1.79

In [35]:
arr=np.arange(25)
ranarr=np.random.randint(1,50,10)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr

array([ 2, 29, 49, 34, 44, 33, 39,  6, 47,  2])

In [38]:
ranarr.max()

49

In [39]:
ranarr.argmax()
# location

2

In [40]:
ranarr.min()

2

In [41]:
ranarr.argmin()

0

In [42]:
arr.shape
# asking vector shape

(25,)

In [46]:
new_arr = arr.reshape(25,1)

In [47]:
new_arr.shape

(25, 1)

In [48]:
new_arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])